trustedshops-public/connect-app-connector

src/modules/dashboard/index.tsx
=> fix var scope issue

src/modules/auth/index.tsx
Said not able to save the changed integration settings. it might be because of regex((/[^a-zA-Z1-9._/-]/g, '')).  I have changed the regex of nameOfSystem to (/[^a-zA-Z0-9._/-]/g, '').
=> fix: nameOfSystem regex

src/baseLayers/testData/getTrustbadgeMock.ts, src/modules/dashboard/tabTrustBadge/parseTrustbadgeData.ts, src/store/trustbadge/getTrustbadgeDefault.ts
Reverts trustedshops-public/connect-app-connector#32
=> Revert "feat: add color mode to Trustbadge"

src/modules/auth/index.tsx
Reverts trustedshops-public/connect-app-connector#28
=> Revert "fix: nameOfSystem regex"

src/baseLayers/testData/getTrustbadgeMock.ts, src/modules/dashboard/tabTrustBadge/parseTrustbadgeData.ts, src/store/trustbadge/getTrustbadgeDefault.ts
=> Revert "Revert "feat: add color mode to Trustbadge""

src/modules/auth/index.tsx
Reverts trustedshops-public/connect-app-connector#37
=> Revert "Revert "fix: nameOfSystem regex""

src/store/reviewInvites/reviewInvitesSendActions.ts
added the recursive function call with patch
called 1s + 2s + 4s + 8s
if a call error falls, then from catch it is called again with an increasing delay, and if the delay is more than 8 seconds, then an error is already thrown into the console.
=> Feat: add delay function

package.json, src/components/layouts/infoBox/index.tsx, src/modules/auth/index.tsx, src/modules/dashboard/index.tsx, src/modules/dashboard/tabReviewInvites/sendReviewInvitesRightTime.tsx, src/modules/dashboard/tabSettings/index.tsx, src/modules/dashboard/tabTrustBadge/editIntegrationCode.tsx, src/modules/dashboard/tabTrustBadge/index.tsx, src/modules/dashboard/tabTrustBadge/trustBadgeSwitcher.tsx, src/modules/dashboard/tabWidgets/index.tsx, src/modules/licences/index.tsx, src/utils.ts, yarn.lock
removed 3 libraries from package.Json (Lodash, yup and @hookform/resolvers)
created a new file for trustBadge switcher.
code splitting.
=> feat: speed improvement

src/baseLayers/testData/getOrderStatuses.ts, src/baseLayers/testData/getUsedOrderStatuses.ts, src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> feat: add orser statuses for TEST

src/locales/keys.ts, src/locales/resources/en-GB.json, src/locales/types.ts, src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx, src/store/reviewInvites/reviewInvitesSendActions.ts, src/store/reviewInvites/reviewInvitesSendActions_v2.ts, tailwind.config.js
=> fix: review invites UI and func fixes

src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx, src/store/reviewInvites/index.ts, src/store/reviewInvites/reviewInvitesSendActions_v2.ts, src/store/reviewInvites/types.ts
=> fix: sonarCloud issue

src/store/reviewInvites/reviewInvitesSendActions.ts, src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> fix:sendAction validation

src/modules/auth/index.tsx, src/modules/dashboard/index.tsx
=> fix: remove lazy() from dashboard

src/modules/auth/index.tsx, src/modules/dashboard/index.tsx, src/modules/dashboard/tabTrustBadge/index.tsx
=> feat: remove lazy imports

src/components/layouts/toast/index.tsx, src/locales/keys.ts, src/locales/types.ts, src/modules/dashboard/channelSelectModal.tsx, src/modules/dashboard/channelSelectionForm.tsx, src/modules/dashboard/index.tsx, src/modules/dashboard/tabReviewInvites/index.tsx, src/modules/dashboard/tabReviewInvites/sendReviewInvitesForPreviousOrders.tsx, src/modules/dashboard/tabReviewInvites/sendReviewInvitesForProducts.tsx, src/modules/dashboard/tabReviewInvites/sendReviewInvitesRightTime.tsx, src/modules/dashboard/tabReviewInvites/v2/ReviewInvitesTab_v2.tsx, src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesForPreviousOrders_v2.tsx, src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx, src/modules/dashboard/tabSettings/approveDisconnectModal.tsx, src/modules/dashboard/tabSettings/index.tsx, src/modules/dashboard/tabTrustBadge/approveDisableModal.tsx, src/modules/dashboard/tabTrustBadge/editIntegrationCode.tsx, src/modules/dashboard/tabTrustBadge/index.tsx, src/modules/dashboard/tabTrustBadge/standartEditor.tsx, src/modules/dashboard/tabTrustBadge/trustBadgeSwitcher.tsx, src/modules/dashboard/tabWidgets/createWidgetPopup.tsx, src/modules/dashboard/tabWidgets/index.tsx, src/modules/dashboard/tabWidgets/widgetExtension.tsx, src/modules/dashboard/tabWidgets/widgetRow.tsx, src/modules/index.ts, src/modules/type.ts, src/utils/lazyLoading.tsx
=> feat: lazy loading

src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> fix: resolve sonar cloud issues

src/locales/resources/de-DE.json, src/locales/resources/en-GB.json, src/locales/resources/es-ES.json, src/locales/resources/fr-FR.json, src/locales/resources/it-IT.json, src/locales/resources/nl-NL.json, src/locales/resources/pl-PL.json, src/locales/resources/pt-PT.json
Exported the most recent locale files from Phrase
=> Updated translations from Phrase

src/locales/keys.ts, src/locales/resources/en-GB.json, src/locales/types.ts, src/modules/dashboard/index.tsx
=> feat: Joint Controllership Agreement

src/modules/dashboard/index.tsx
=> bug: add action for product id

src/locales/keys.ts, src/locales/resources/en-GB.json, src/locales/types.ts, src/modules/dashboard/index.tsx
=> fix:add missing code

src/components/controls/input/index.tsx, src/modules/dashboard/channelSelectionForm.tsx, src/modules/dashboard/index.tsx, src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx, tailwind.config.js
=> fix: reviews label width issue

src/baseLayers/testData/getInformationOfSystem.ts, src/modules/dashboard/index.tsx
=> fix: allowsEstimatedDeliveryDate inpact on v2

src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> fix: Deactivate Invite-Settings with the wrong payload

src/modules/dashboard/channelSelectModal.tsx, src/modules/dashboard/index.tsx, src/modules/dashboard/tabSettings/index.tsx, src/store/reviewInvites/reviewInvitesSendActions_v2.ts, src/store/reviewInvites/types.ts
=> fix: initial order status

src/components/controls/dropdown/option.tsx, src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx
=> feat: order dropdown adaptions

src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> feat: order dropdown improvements

src/modules/dashboard/tabReviewInvites/v2/ReviewInvitesTab_v2.tsx, src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx, src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> feat: event duplication fix

src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> feat: loading twice issue

src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> feat: loading issue fix

src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx
=> fix: debugging prestashop issue

src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> fix: debugging prestashop

src/tests/resources/requirements.txt
=> fix: test failing improvement

.circleci/config.yml
=> fix: downgrade python

src/components/controls/tag/index.tsx, src/modules/dashboard/tabWidgets/widgetRow.tsx
=> fix: ui fixes lightspeed framework too narrow

src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx, src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> feat: removed logging for prod

src/components/layouts/tabs/index.tsx
=> fix: tab ids to numbers

src/components/layouts/tabs/index.tsx, src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx
=> fix: order status ids to string

src/components/layouts/tabs/index.tsx
=> fix: revert changes of test

src/components/layouts/tabs/index.tsx, src/tests/resources/keywords/Header.robot
=> fix: tab ids correction

src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> fix: converting IDs to string of available order statuses

src/components/controls/dropdown/select.tsx, src/modules/dashboard/channelSelectionForm.tsx
=> fix: test id selector of channels

src/components/controls/dropdown/option.tsx, src/components/controls/dropdown/select.tsx, src/modules/dashboard/channelSelectionForm.tsx, src/modules/dashboard/index.tsx, src/modules/dashboard/tabTrustBadge/standartEditor.tsx, src/modules/dashboard/tabWidgets/widgetRow.tsx, src/tests/resources/keywords/ChannelMappingCommon.robot, src/tests/resources/keywords/ChannelMappingPopup.robot, src/tests/resources/keywords/SettingsTab.robot
=> fix: revert test id selector of channels

src/modules/dashboard/index.tsx, src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> fix: logs for magento

src/modules/dashboard/index.tsx, src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> fix: magento fix for available order statuses

src/components/controls/dropdown/option.tsx, src/components/controls/dropdown/select.tsx, src/modules/dashboard/channelSelectionForm.tsx, src/modules/dashboard/index.tsx, src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx, src/modules/dashboard/tabTrustBadge/standartEditor.tsx, src/modules/dashboard/tabWidgets/widgetRow.tsx
=> fix: test ids improvement

src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesForPreviousOrders_v2.tsx
=> fix: Static text replaced with the right translation key

src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx, src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> fix: id null toString fix

.env.development, .env.production, .env.test, src/api/api.ts, src/modules/dashboard/channelSelectModal.tsx, src/modules/dashboard/tabReviewInvites/index.tsx, src/modules/dashboard/tabReviewInvites/sendReviewInvitesForPreviousOrders.tsx, src/modules/dashboard/tabReviewInvites/v2/ReviewInvitesTab_v2.tsx, src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesForPreviousOrders_v2.tsx, src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx, src/modules/dashboard/tabSettings/index.tsx, src/modules/dashboard/tabTrustBadge/index.tsx, src/modules/dashboard/tabWidgets/index.tsx, src/store/selector.ts, src/utils/configurationDataHandler.tsx
=> feat: Configuration Data

.env.development
=> Feat: Qa env fix

src/locales/types.ts, src/modules/dashboard/channelSelectModal.tsx, src/modules/dashboard/tabReviewInvites/index.tsx, src/modules/dashboard/tabReviewInvites/sendReviewInvitesForPreviousOrders.tsx, src/modules/dashboard/tabReviewInvites/v2/ReviewInvitesTab_v2.tsx, src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesForPreviousOrders_v2.tsx, src/modules/dashboard/tabReviewInvites/v2/sendReviewInvitesRightTime_v2.tsx, src/modules/dashboard/tabSettings/index.tsx, src/modules/dashboard/tabTrustBadge/index.tsx, src/modules/dashboard/tabWidgets/index.tsx, src/store/selector.ts, src/utils/configurationDataHandler.tsx
=> Added selectedTab on the payload

src/modules/dashboard/tabReviewInvites/index.tsx
=> Added missing saving config for toggle button for invitesForProducts

LICENSE.txt
=> TPSCON-2874 AG to SE change

src/modules/dashboard/channelSelectionForm.tsx
=> fix: Translations reinitialise semantic release

src/modules/dashboard/channelSelectModal.tsx, src/modules/dashboard/tabSettings/index.tsx
=> fix: TPSCON-3080 Product Reviews deactivation after installing Shoper

src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> fix: TPSCON-2367 Sonarcloud issue

src/store/reviewInvites/reviewInvitesSendActions_v2.ts
=> fix: TPSCON-2367 Sonarcloud issue fix

src/modules/dashboard/index.tsx
=> fix: TPSCON-3076 Missing Channel Payload

src/modules/dashboard/index.tsx
=> fix: TPSCON-3076 Missing Selected Channels Payload

.circleci/config.yml
- Update config.yml file to display trigerred automated tests pipeline URL in the logs
=> feat: TPSCON-3619 Configure automated tests in the dev pipeline
